### ISSUE TITLE
Detached Payload in Consistency Proofs

### ISSUE THREAD

**Issue by OR13** [cose-wg/draft-ietf-cose-merkle-tree-proofs#30]
https://mailarchive.ietf.org/arch/msg/cose/Jr10No1nSA35PxhBzYmx49oYuuY/

Some discussion on the list suggests that both inclusion and consistency proofs should have detached payloads.

**Comment by OR13** [comment]
Changes suggested in Section 5.3.1 https://datatracker.ietf.org/doc/html/draft-ietf-cose-merkle-tree-proofs-05#section-5.3.1-8

**Comment by OR13** [comment]
Lets add a sentence explaining why consistency proof needs to be attached, and that verifying a consistency proof starts with having 2 roots... so detaching is not recommended

**Comment by robinbryce** [comment]
This is very specific to this particular VDS. And I still I don't know why it would not be recommended. The reasons it make sense to require the root of a inclusion proof be generated as part of signature verification seem to apply at least to the second root.

I supsect the reason here is "because this is how we did it" ?

**Comment by robinbryce** [comment]
I'll try a pr for this this week, unless someone beats me to i

**Comment by SteveLasker** [comment]
Editor's call note: For RFC9162 consistency proofs, we should have an attached payload, which is the new merkletree head, for this particular format.
